'use client';
import {useEffect,useRef,useState} from 'react';
import {useTimeZone} from './time-zone';
import {dateInZone,formatInstant} from '@/lib/erp/time-zone';
import {money} from './presentation';
const labels:Record<string,string>={EXPENSE:'營運支出',INCOME:'其他收入',CAPITAL_IN:'資金轉入',CAPITAL_OUT:'資金轉出'};
const categories:Record<string,string[]>={EXPENSE:['薪資','租金','水電','運費','耗材','其他費用'],INCOME:['利息','服務收入','其他收入'],CAPITAL_IN:['老闆投入','借入款','其他資金轉入'],CAPITAL_OUT:['老闆提領','償還借款本金','其他資金轉出']};
type Summary={month:string;gross:string|null;expense:string;income:string;profit:string|null;capitalIn:string;capitalOut:string};
type Values={date:string;kind:string;category:string;amount:string;currency:string;fxToAud:string;account:string;counterparty:string;note:string};
type Entry=Values&{id:string;actor:string;amountAud:string;version:number;voided:boolean;history:{id:string;time:string;actor:string;action:string;reason:string|null;before:Values|null;after:Values&{voided?:boolean}}[]};
type Employee={id:string;displayName:string;email:string;employeeRole:string;cashView:boolean;cashEdit:boolean;updatedAt:string;active:boolean};
type Ledger={summary:Summary;edit:boolean;admin:boolean;entries:Entry[];employees:Employee[]};
async function read(month:string,summary=false){const r=await fetch('/api/erp/cash?month='+month+(summary?'&summary=1':''),{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'讀取失敗');return d;}
function SummaryCards({s}:{s:Summary}){return <><div className="daily-metrics"><article className="daily-card accent-blue"><small>已出貨毛利 · AUD</small><strong>{money(s.gross)}</strong></article><article className="daily-card accent-green"><small>其他收入 · AUD</small><strong>{money(s.income)}</strong></article><article className="daily-card accent-amber"><small>營運費用 · AUD</small><strong>{money(s.expense)}</strong></article><article className="daily-card accent-purple"><small>營運損益 · AUD</small><strong>{money(s.profit)}</strong></article></div><p className="accounting-note">營運損益＝已出貨毛利＋其他收入－營運費用。依填寫日期統計；不含資金投入、借還款本金與提領，亦非銀行餘額。</p>{s.profit===null&&<p role="status" className="notice error">本月出貨缺少匯率或鎖定成本，無法計算完整營運損益。</p>}</>;}
export function MonthlyCashSummary({refresh,navigate}:{refresh:string;navigate:()=>void}){
 const {zone}=useTimeZone();const month=dateInZone(new Date(refresh),zone).slice(0,7);const [s,setS]=useState<Summary|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let live=true;setS(null);setError('');read(month,true).then(d=>{if(live)setS(d.summary);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[month,refresh,retry]);
 return <section className="panel"><div className="section-heading"><h2>本月營運損益 <small>{month}</small></h2><button className="text-action" onClick={navigate}>收支管理 →</button></div>{s?<SummaryCards s={s}/>:error?<p role="alert">{error} <button className="quiet" onClick={()=>setRetry(v=>v+1)}>重試</button></p>:<p role="status">正在讀取本月收支…</p>}</section>;
}
export default function CashManagement({refresh}:{refresh:string}){
 const {zone}=useTimeZone();const today=dateInZone(new Date(),zone);const [month,setMonth]=useState(today.slice(0,7)),[data,setData]=useState<Ledger|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
 const [editing,setEditing]=useState<Entry|'new'|null>(null),[kind,setKind]=useState(''),[category,setCategory]=useState(''),[showVoid,setShowVoid]=useState(false);
 const pending=useRef<{payload:string;key:string}|null>(null);
 useEffect(()=>{let live=true;setData(null);setError('');read(month).then(d=>{if(live)setData(d);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[month,refresh,revision]);
 async function save(input:Record<string,unknown>){if(busy)return false;setBusy(true);setError('');setMessage('');const payload=JSON.stringify(input);if(pending.current?.payload!==payload)pending.current={payload,key:crypto.randomUUID()};try{const r=await fetch('/api/erp/cash',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,requestKey:pending.current.key})});const result=await r.json();if(!r.ok)throw Error(result.error);pending.current=null;setEditing(null);setMessage('已儲存，操作紀錄已保留。');setRevision(v=>v+1);return true;}catch(e){setError(e instanceof Error?e.message:'儲存失敗');return false;}finally{setBusy(false);}}
 const rows=data?.entries.filter(e=>(showVoid||!e.voided)&&(!kind||kind===e.kind)&&(!category||category===e.category))||[];
 return <><section className="panel"><div className="section-heading"><h2>每月收支與損益</h2><label>統計月份<input type="month" value={month} disabled={busy} onChange={e=>{if(/^\d{4}-(0[1-9]|1[0-2])$/.test(e.target.value)){setMonth(e.target.value);setEditing(null);setCategory('');}}}/></label></div>{data&&<><SummaryCards s={data.summary}/><div className="chips"><span>資金轉入 AUD {money(data.summary.capitalIn)}</span><span>資金轉出 AUD {money(data.summary.capitalOut)}</span></div></>}<p className="accounting-note">收支請按實際收付款日期登記。貨款在「客戶帳款」登記；商品進貨成本沿用既有批次帳務，不在此重複登記。借款利息屬費用，本金屬資金往來。</p></section>
 {error&&<div role="alert" className="notice error">{error} <button className="quiet" disabled={busy} onClick={()=>setRevision(v=>v+1)}>重新讀取</button></div>}{message&&<p role="status" className="notice">{message}</p>}{!data&&!error&&<p role="status">正在讀取收支…</p>}
 {data&&<><section className="panel"><div className="section-heading"><h2>收支紀錄</h2>{data.edit&&<button className="primary" disabled={busy} onClick={()=>setEditing('new')}>＋ 新增收支</button>}</div>
 {editing&&<CashForm key={typeof editing==='string'?'new':editing.id} entry={editing==='new'?undefined:editing} today={today} busy={busy} save={save} cancel={()=>setEditing(null)}/>}
 <div className="form-grid"><label>類型<select value={kind} onChange={e=>{setKind(e.target.value);setCategory('');}}><option value="">全部類型</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>分類<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">全部分類</option>{[...new Set(data.entries.filter(e=>!kind||e.kind===kind).map(e=>e.category))].sort().map(v=><option key={v}>{v}</option>)}</select></label><label>作廢紀錄<select value={showVoid?'all':'active'} onChange={e=>setShowVoid(e.target.value==='all')}><option value="active">僅有效紀錄</option><option value="all">含作廢紀錄</option></select></label></div><p className="accounting-note">共 {rows.length} 筆；上方總覽為整月合計，不受類型與分類篩選影響。</p>
 <div className="cash-list">{rows.map(e=><article className="cash-card" key={e.id}><div className="section-heading"><div><strong>{e.date} · {labels[e.kind]} · {e.category}</strong><p>{e.account}{e.counterparty?' · '+e.counterparty:''}</p></div><div><strong>{e.currency} {money(e.amount)}</strong><small className="cash-secondary">AUD {money(e.amountAud)}{e.voided?' · 已作廢':''}</small></div></div>{e.note&&<p className="cash-note">{e.note}</p>}<small>經手人：{e.actor} · 1 {e.currency} = {e.fxToAud} AUD</small><div className="cash-actions">{data.edit&&!e.voided&&<><button className="quiet" disabled={busy} onClick={()=>setEditing(e)}>編輯</button><button className="quiet" disabled={busy} onClick={()=>{const reason=window.prompt('作廢會保留紀錄，且不再計入收支。請輸入原因：');if(reason?.trim())void save({action:'cashVoid',id:e.id,version:e.version,reason:reason.trim()});}}>作廢</button></>}</div><details><summary>異動紀錄（{e.history.length}）</summary>{e.history.map(h=><div className="cash-history" key={h.id}><small>{formatInstant(h.time,zone)} · {h.actor} · {h.action==='cashCreate'?'新增':h.action==='cashEdit'?'修改':'作廢'}</small>{h.reason&&<p>原因：{h.reason}</p>}{h.before&&<p>修改前：{describe(h.before)}</p>}<p>{h.after.voided?'作廢資料':'儲存資料'}：{describe(h.after)}</p></div>)}</details></article>)}</div>{!rows.length&&<p className="accounting-note">此月份沒有符合條件的收支紀錄。</p>}</section>
 {data.admin&&<section className="panel"><h2>收支權限</h2><p className="accounting-note">管理員與主管具有完整權限。以下權限可查看所有收支（包含薪資與資金往來）；新增／修改權限包含作廢。</p>{data.employees.filter(e=>e.employeeRole!=='MANAGER').map(e=><form className="cash-permission" key={e.id+e.updatedAt} onSubmit={ev=>{ev.preventDefault();const f=new FormData(ev.currentTarget);const access=String(f.get('access'));void save({action:'cashPermission',id:e.id,expectedUpdatedAt:e.updatedAt,cashView:access!=='none',cashEdit:access==='edit'});}}><div><strong>{e.displayName||e.email}</strong><small className="cash-secondary">{e.email}{!e.active?' · 已停用':''}</small></div><label>收支權限<select name="access" defaultValue={e.cashEdit?'edit':e.cashView?'view':'none'} disabled={busy}><option value="none">無權限</option><option value="view">僅查看</option><option value="edit">查看、新增、修改及作廢</option></select></label><button className="quiet" disabled={busy}>儲存權限</button></form>)}</section>}</>}
 </>;
}
function describe(v:Values){return `${v.date.slice(0,10)} · ${labels[v.kind]||v.kind} · ${v.category} · ${v.currency} ${v.amount} · 匯率 ${v.fxToAud} · ${v.account} · ${v.counterparty||'—'} · ${v.note||'—'}`;}
function CashForm({entry,today,busy,save,cancel}:{entry?:Entry;today:string;busy:boolean;save:(v:Record<string,unknown>)=>Promise<boolean>;cancel:()=>void}){
 const [kind,setKind]=useState(entry?.kind||'EXPENSE'),[currency,setCurrency]=useState(entry?.currency||'AUD');
 return <form className="cash-form" onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));void save({...f,fxToAud:currency==='AUD'?'1':f.fxToAud,action:entry?'cashEdit':'cashCreate',...(entry?{id:entry.id,version:entry.version}:{})});}}><h3>{entry?'編輯收支':'新增收支'}</h3><fieldset disabled={busy}><div className="form-grid"><label>收付款日期<input name="date" type="date" required defaultValue={entry?.date||today}/></label><label>類型<select name="kind" value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>分類（可自行輸入）<input key={kind} name="category" list="cash-categories" required maxLength={160} defaultValue={entry?.kind===kind?entry.category:categories[kind][0]}/><datalist id="cash-categories">{categories[kind].map(v=><option key={v} value={v}/>)}</datalist></label><label>金額<input name="amount" type="number" min="0.01" max="9999999999.99" step="0.01" required defaultValue={entry?.amount}/></label><label>幣別<select name="currency" value={currency} onChange={e=>setCurrency(e.target.value)}><option>AUD</option><option>CNY</option></select></label>{currency==='CNY'&&<label>匯率（1 CNY = 多少 AUD）<input name="fxToAud" type="number" min="0.00000001" max="999999.99999999" step="0.00000001" required defaultValue={entry?.currency==='CNY'?entry.fxToAud:undefined}/></label>}<label>收付款帳戶<input name="account" placeholder="例如：現金、公司銀行" required maxLength={160} defaultValue={entry?.account}/></label><label>對象（選填）<input name="counterparty" maxLength={160} defaultValue={entry?.counterparty}/></label><label>用途／備註（選填）<textarea name="note" maxLength={2000} defaultValue={entry?.note}/></label>{entry&&<label>修改原因<input name="reason" required maxLength={160}/></label>}</div><div className="cash-actions"><button className="primary">{busy?'儲存中…':'儲存收支'}</button><button type="button" className="quiet" onClick={cancel}>取消</button></div></fieldset></form>;
}
