'use client';
/* eslint-disable @next/next/no-img-element -- Preview uses locally generated PNG blob URLs, not remote images. */
import {useEffect,useRef,useState} from 'react';
import type {OrderDocument} from '@/lib/erp/document-types';
import {renderDocument} from '@/lib/erp/render-document';
export default function DocumentPreview({orderId,shipmentId,onClose}:{orderId:string;shipmentId?:string;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const [data,setData]=useState<OrderDocument|null>(null),[company,setCompany]=useState('庫務 ERP'),[note,setNote]=useState(false),[urls,setUrls]=useState<string[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{dialog.current?.showModal();const abort=new AbortController();fetch('/api/erp/documents?'+new URLSearchParams({orderId,...(shipmentId?{shipmentId}:{})}),{cache:'no-store',signal:abort.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);}).catch(e=>{if(e.name!=='AbortError'){setError(e.message);setLoading(false);}});return()=>abort.abort();},[orderId,shipmentId]);
 useEffect(()=>{if(!data)return;let cancelled=false;const created:string[]=[];setLoading(true);setUrls([]);setError('');const timer=setTimeout(()=>{renderDocument(data,company,note).then(blobs=>{if(cancelled)return;for(const blob of blobs)created.push(URL.createObjectURL(blob));setUrls([...created]);setLoading(false);}).catch(e=>{if(!cancelled){setError(e.message);setLoading(false);}});},200);return()=>{cancelled=true;clearTimeout(timer);created.forEach(url=>URL.revokeObjectURL(url));};},[data,company,note]);
 return <dialog ref={dialog} aria-labelledby="document-title" onCancel={onClose} style={{width:'min(850px, 95vw)',maxHeight:'92vh',padding:24,border:'1px solid #ccd9dd',borderRadius:12,overflow:'auto'}}><div className="section-heading"><h2 id="document-title">{shipmentId?'出貨單圖片':'訂單明細圖片'}</h2><button type="button" onClick={onClose}>關閉預覽</button></div><label>公司／店名（本次圖片）<input maxLength={80} value={company} onChange={e=>setCompany(e.target.value)}/></label>{data?.note&&<label><input type="checkbox" checked={note} onChange={e=>setNote(e.target.checked)} style={{width:'auto'}}/> 附上備註（請先確認內容可提供客戶）</label>}<p>圖片不含成本與毛利。收款依開啟預覽時的資料及帳號權限顯示；需要最新數字請關閉後重新開啟。</p>{error&&<p role="alert">{error}</p>}{loading&&<p role="status">正在產生圖片…</p>}{!loading&&urls.map((url,i)=><div key={url} style={{marginTop:20}}><a className="btn-primary" href={url} download={`${data?.number.replace(/[^a-zA-Z0-9_-]/g,'_')}-${i+1}.png`}>下載 PNG{urls.length>1?`（第 ${i+1} 頁）`:''}</a><p>手機若未直接下載，可長按下方圖片儲存。</p><img src={url} alt={`${shipmentId?'出貨單':'訂單明細'}預覽第 ${i+1} 頁`} style={{width:'100%',height:'auto',border:'1px solid #ddd'}}/></div>)}</dialog>;
}
