'use client';
import {useState} from 'react';
import ActionDrawer from './action-drawer';
import {employeeEditError} from '@/lib/erp/employee-policy';
export type Employee={id:string;email:string;displayName:string;employeeRole:string|null;role:string;active:boolean;updatedAt:string};
const roles:Record<string,string>={ADMIN:'系統管理員',MANAGER:'主管',WAREHOUSE:'倉管',SALES:'業務',FINANCE:'財務'};
const descriptions:Record<string,string>={ADMIN:'管理全部 ERP 功能、員工及密碼重設。',MANAGER:'管理 ERP 帳務與一般員工；不能管理其他主管或管理員。',WAREHOUSE:'查詢商品與庫存、確認出貨；不顯示成本、毛利與收款。',SALES:'查詢庫存、建立客戶與銷售單；不顯示成本、毛利與收款。',FINANCE:'查詢帳務、成本與毛利、登錄收款；不能管理員工。'};
type Props={user:{id:string;admin:boolean};employees:Employee[];busy:boolean;error:string;save:(input:Record<string,unknown>,form?:HTMLFormElement)=>Promise<boolean>};
export default function EmployeeManagement({user,employees,busy,error,save}:Props){
 const [target,setTarget]=useState<Employee|null>(null),[role,setRole]=useState('WAREHOUSE'),[active,setActive]=useState(true),[failure,setFailure]=useState(false);
 const actor={id:user.id,role:user.admin?'ADMIN':'BUYER',employeeRole:user.admin?null:'MANAGER',active:true};
 const available=Object.keys(roles).filter(r=>r!=='ADMIN'&&(user.admin||r!=='MANAGER'));
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);await save({action:'employee',email:f.get('email'),name:f.get('name'),password:f.get('password'),role:f.get('role')},form);}
 async function edit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!target)return;setFailure(false);const f=new FormData(e.currentTarget);if(await save({action:'editEmployee',id:target.id,expectedUpdatedAt:target.updatedAt,email:f.get('email'),name:f.get('name'),role,active}))setTarget(null);else setFailure(true);}
 return <section className="panel"><h2>員工與權限</h2><p>新增或編輯員工資料、角色與啟用狀態。密碼修改與重設請到「09 帳號管理」。</p><form onSubmit={create}><fieldset disabled={busy}><div className="form-grid"><label>Email<input name="email" type="email" autoComplete="off" maxLength={160} required/></label><label>員工姓名<input name="name" autoComplete="off" maxLength={160} required/></label><label>初始密碼（至少 8 碼）<input name="password" type="password" autoComplete="new-password" minLength={8} maxLength={72} required/></label><label>權限<select name="role" defaultValue="WAREHOUSE">{available.map(r=><option key={r} value={r}>{roles[r]}</option>)}</select></label></div><button className="primary" disabled={busy}>建立員工</button></fieldset></form>
 <div className="table-scroll employee-table"><table><thead><tr><th>員工／Email</th><th>角色</th><th>狀態</th><th>操作</th></tr></thead><tbody>{employees.map(e=>{const currentRole=e.role==='ADMIN'?'ADMIN':e.employeeRole||'';const deny=employeeEditError(actor,e,{role:currentRole,active:e.active});return <tr key={e.id}><td>{e.displayName||'未設定姓名'}{e.id===user.id&&'（本人）'}<small>{e.email}</small></td><td>{roles[currentRole]||currentRole}</td><td><span className={'status-pill '+(e.active?'status-green':'status-neutral')}>{e.active?'啟用':'停用'}</span></td><td>{!deny?<button className="quiet" disabled={busy} onClick={()=>{setTarget(e);setRole(currentRole);setActive(e.active);setFailure(false);}}>編輯員工</button>:<small>{e.role==='ADMIN'?'管理員管理':'僅管理員可編輯'}</small>}</td></tr>})}</tbody></table></div>
 <details className="employee-role-guide"><summary>角色權限說明</summary>{Object.entries(descriptions).map(([r,d])=><p key={r}><strong>{roles[r]}：</strong>{d}</p>)}</details>
 {target&&<ActionDrawer title="編輯員工資料" busy={busy} close={()=>setTarget(null)}><form onSubmit={edit}><fieldset disabled={busy}><p className="drawer-intro">更新既有帳號；歷史單據仍保留與同一位員工的關聯。</p>{failure&&<p role="alert" className="notice error">{error||'儲存失敗，請稍後重試。'}</p>}<label>Email<input type="email" name="email" defaultValue={target.email} autoComplete="off" maxLength={160} required/></label><label>員工姓名<input name="name" defaultValue={target.displayName} autoComplete="off" maxLength={160} required/></label><label>角色<select aria-label="員工角色" value={role} disabled={target.id===user.id||target.role==='ADMIN'} onChange={e=>setRole(e.target.value)}>{[...new Set([...available, ...(target.role==='ADMIN'?['ADMIN']:target.id===user.id?['MANAGER']:[])])].map(r=><option key={r} value={r}>{roles[r]}</option>)}</select></label><p className="form-hint">{descriptions[role]}</p><label>帳號狀態<select aria-label="帳號狀態" value={active?'enabled':'disabled'} disabled={target.id===user.id||target.role==='ADMIN'} onChange={e=>setActive(e.target.value==='enabled')}><option value="enabled">啟用</option><option value="disabled">停用</option></select></label>{(target.id===user.id||target.role==='ADMIN')&&<p className="form-hint">自己與系統管理員的角色、啟用狀態不可在此變更。</p>}<p className="form-hint">Email 更新後請使用新 Email 登入；角色與停用設定會在後續請求生效。密碼不會改變。</p><div className="drawer-submit"><button className="primary" disabled={busy}>{busy?'儲存中…':'儲存員工資料'}</button></div></fieldset></form></ActionDrawer>}
 </section>;
}
