'use client';
import type {Data} from './workspace';
import {MiniIcon,money,orderStatus,Status} from './presentation';
export default function Overview({data,navigate,openOrder}:{data:Data;navigate:(tab:string)=>void;openOrder:(number:string)=>void}){
 const pending=data.orders.filter(o=>o.lines.some(l=>l.remaining>0));
 const partial=pending.filter(o=>orderStatus(o)==='部分出貨');
 const unpaid=data.orders.filter(o=>o.due!==null&&Number(o.due)>0);
 const units=[...new Set(data.inventory.map(i=>i.unit))];
 const inventory=units.map(unit=>({unit,total:data.inventory.filter(i=>i.unit===unit).reduce((n,i)=>n+i.total,0)}));
 return <div className="overview-view">
 <section className="overview-banner"><div><span className="banner-kicker">YOUR WORKSPACE, AT A GLANCE</span><h2>營運有序，掌握每一步。</h2><p>{pending.length?`目前有 ${pending.length} 張訂單等待出貨，從這裡開始今天的工作。`:'出貨工作已就緒，從這裡開始今天的營運。'}</p></div><button onClick={()=>navigate('sales')}>前往銷售與出貨 <span aria-hidden="true">↗</span></button></section>
 <div className="dashboard-metrics">
 <button className="metric-card" onClick={()=>navigate('stock')}><span className="metric-top">現有庫存 <span className="metric-icon"><MiniIcon kind="stock"/></span></span><strong className="inventory-value">{inventory.length?inventory.map(i=><span key={i.unit}>{i.total.toLocaleString()}<em>{i.unit}</em></span>):'0'}</strong><span className="metric-foot">{data.skus.length} 個 SKU · {data.warehouses.length} 個倉庫 <b>↗</b></span></button>
 <button className="metric-card" onClick={()=>navigate('sales')}><span className="metric-top">待出貨訂單 <span className="metric-icon amber"><MiniIcon kind="orders"/></span></span><strong>{pending.length}<em>張</em></strong><span className="metric-foot">其中 {partial.length} 張已部分出貨 <b>↗</b></span></button>
 {data.user.financial&&<><button className="metric-card" onClick={()=>navigate('payments')}><span className="metric-top">客戶未收款 <span className="metric-icon blue"><MiniIcon kind="money"/></span></span><strong><small>AUD</small>{money(data.totals.due)}</strong><span className="metric-foot">含尚未出貨訂單 · {unpaid.length} 張待收款 <b>↗</b></span></button><button className="metric-card" onClick={()=>navigate('batches')}><span className="metric-top">已出貨毛利 <span className="metric-icon"><MiniIcon kind="profit"/></span></span><strong><small>AUD</small>{money(data.totals.profit)}</strong><span className="metric-foot">累計毛利 · 未扣營運費用 <b>↗</b></span></button></>}
 </div>
 {data.user.financial&&(data.totals.due===null||data.totals.profit===null)&&<p className="form-hint">部分交易尚缺匯率或成本，無法換算的合計以「—」顯示。</p>}
 <div className="overview-grid"><section className="panel recent-orders"><div className="section-heading"><div><p className="section-kicker">RECENT ORDERS</p><h2>最近訂單</h2></div><button className="text-action" onClick={()=>navigate('sales')}>查看全部 ↗</button></div><div className="table-scroll"><table><thead><tr><th>訂單／客戶</th><th>出貨狀態</th><th className="numeric">銷售額</th><th><span className="sr-only">操作</span></th></tr></thead><tbody>{data.orders.slice(0,6).map(o=><tr key={o.id}><td><button className="order-link" onClick={()=>openOrder(o.number)}>{o.number}</button><small>{o.customer}</small></td><td><Status value={orderStatus(o)}/></td><td className="numeric"><small>{o.currency}</small><strong>{money(o.total)}</strong></td><td><button className="row-arrow" aria-label={'查看訂單 '+o.number} onClick={()=>openOrder(o.number)}>↗</button></td></tr>)}</tbody></table></div>{!data.orders.length&&<div className="designed-empty"><MiniIcon kind="orders"/><h3>準備好第一筆交易</h3><p>建立商品與客戶後，即可開始記錄銷售訂單。</p><button className="quiet" onClick={()=>navigate('sales')}>前往銷售與出貨</button></div>}</section>
 <section className="panel work-queue"><p className="section-kicker">NEXT UP</p><h2>待辦與快速入口</h2><button className="queue-item" onClick={()=>navigate('sales')}><span className="queue-icon">↗</span><span><strong>安排出貨</strong><small>{pending.length} 張訂單待處理</small></span><b>{pending.length}</b></button>{data.user.financial&&<button className="queue-item" onClick={()=>navigate('payments')}><span className="queue-icon amber">＄</span><span><strong>追蹤收款</strong><small>查看客戶未收款明細</small></span><b>{unpaid.length}</b></button>}<div className="quick-links"><button onClick={()=>navigate('stock')}>商品與庫存 <span>→</span></button>{data.user.permissions.includes('receive')&&<button onClick={()=>navigate('receive')}>採購入庫 <span>→</span></button>}<button onClick={()=>navigate('settings')}>客戶與基礎資料 <span>→</span></button></div><p className="queue-note">每次入庫、出貨與收款，都會留下操作紀錄。</p></section></div>
 </div>;
}
