'use client';
import {useState} from 'react';
import type {Data} from './workspace';
import type {DailyProfit} from '@/lib/erp/daily-profit';
import {money,orderStatus,Status} from './presentation';
import {useTimeZone} from './time-zone';
import {dateInZone} from '@/lib/erp/time-zone';
import {ProfitTrend,OrderDistribution} from './dashboard-charts';
const emptyDay=(date:string):DailyProfit=>({date,revenue:'0.00',cost:'0.00',profit:'0.00',margin:null,shipments:0,orders:0,incomplete:0});
export default function Overview({data,navigate,openOrder}:{data:Data;navigate:(tab:string)=>void;openOrder:(number:string)=>void}){
 const {zone}=useTimeZone();const today=dateInZone(new Date(data.generatedAt),zone);const [chosen,setChosen]=useState('');const selected=chosen||today;
 const days=Array.from({length:7},(_,i)=>{const d=new Date(selected+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-6+i);const date=d.toISOString().slice(0,10);return data.dailyProfit?.find(v=>v.date===date)||emptyDay(date);});
 const daily=days[6];const pending=data.orders.filter(o=>o.lines.some(l=>l.remaining>0));
 const counts=[{name:'待出貨',color:'#e2a54c'},{name:'部分出貨',color:'#26a7bd'},{name:'已出貨',color:'#20b995'}].map(c=>({...c,count:data.orders.filter(o=>orderStatus(o)===c.name).length}));
 const inventory=[...new Set(data.inventory.map(i=>i.unit))].map(unit=>({unit,total:data.inventory.filter(i=>i.unit===unit).reduce((n,i)=>n+i.total,0)}));
 return <div className="business-dashboard"><div className="dashboard-period"><div><h2>{data.user.financial?'每日經營數據':'營運狀態'}</h2><p>{data.user.financial?'銷售額與毛利僅計已確認出貨；金額統一換算 AUD。':'查看庫存、待出貨訂單與出貨進度。'}</p></div>{data.user.financial&&<div className="period-controls"><label>統計日期<input aria-label="統計日期" type="date" value={selected} onChange={e=>{if(/^\d{4}-\d{2}-\d{2}$/.test(e.target.value)&&!Number.isNaN(Date.parse(e.target.value)))setChosen(e.target.value);}}/></label><button className="quiet" onClick={()=>setChosen('')}>今天</button></div>}</div>
 {data.user.financial&&<><div className="daily-metrics"><article className="daily-card accent-blue"><small>出貨銷售額 · AUD</small><strong>{money(daily.revenue)}</strong><span>{selected} · 已確認出貨</span></article><article className="daily-card accent-amber"><small>出貨成本 · AUD</small><strong>{money(daily.cost)}</strong><span>出貨時鎖定成本</span></article><article className={'daily-card accent-green '+(Number(daily.profit)<0?'negative':'')}><small>每日毛利 · AUD</small><strong>{money(daily.profit)}</strong><span>出貨銷售額 − 出貨成本</span></article><article className="daily-card accent-purple"><small>毛利率</small><strong>{daily.margin===null?'—':daily.margin+'%'}</strong><span>毛利 ÷ 出貨銷售額</span></article></div><p className="accounting-note">按填寫的出貨日期統計，排除已沖銷出貨。毛利未扣租金、薪資及其他營運費用。</p>{daily.incomplete>0&&<p className="notice error" role="status">當日有 {daily.incomplete} 筆出貨缺少匯率或鎖定成本；相關合計顯示「—」，不以零代替。</p>}</>}
 <div className="daily-metrics secondary-metrics">{data.user.financial?<><article className="daily-card accent-green"><small>當日銷售單</small><strong>{daily.orders}<em>張</em></strong><span>依銷售日期</span></article><article className="daily-card accent-blue"><small>當日出貨單</small><strong>{daily.shipments}<em>筆</em></strong><span>依出貨日期 · 不含沖銷</span></article></>:<><button className="daily-card accent-green" onClick={()=>navigate('stock')}><small>商品 SKU</small><strong>{data.skus.length}</strong><span>{data.warehouses.length} 個倉庫</span></button><button className="daily-card accent-blue" onClick={()=>navigate('stock')}><small>現有庫存</small><strong className="compact-stock">{inventory.map(i=><span key={i.unit}>{i.total.toLocaleString()}<em>{i.unit}</em> </span>)}</strong><span>各倉庫加總</span></button></>}
 <button className="daily-card accent-amber" onClick={()=>navigate('sales')}><small>待出貨訂單</small><strong>{pending.length}<em>張</em></strong><span>全部訂單 · 含部分出貨 ↗</span></button>{data.user.financial?<button className="daily-card accent-purple" onClick={()=>navigate('payments')}><small>客戶未收款 · AUD</small><strong>{money(data.totals.due)}</strong><span>目前累計 · 非當日金額 ↗</span></button>:<button className="daily-card accent-purple" onClick={()=>navigate('sales')}><small>訂單總數</small><strong>{data.orders.length}<em>張</em></strong><span>查看所有銷售單 ↗</span></button>}</div>
 <div className={'dashboard-charts '+(!data.user.financial?'single-chart':'')}>{data.user.financial&&<section className="panel chart-panel"><div className="section-heading"><h2>近 7 日銷售與毛利</h2><small>{days[0].date} — {selected}</small></div><ProfitTrend days={days}/>{days.some(d=>d.incomplete>0)&&<p className="accounting-note">缺少匯率或成本的日期不繪製相關數值，請展開每日數字確認。</p>}</section>}<section className="panel chart-panel"><div className="section-heading"><h2>訂單出貨狀態</h2><small>全部訂單 · 目前狀態</small></div><OrderDistribution counts={counts}/></section></div>
 <section className="panel dashboard-orders"><div className="section-heading"><h2>最近訂單</h2><button className="text-action" onClick={()=>navigate('sales')}>查看全部 →</button></div><div className="table-scroll"><table><thead><tr><th>訂單編號</th><th>客戶</th><th>銷售日期</th><th className="numeric">訂單金額</th><th>出貨狀態</th>{data.user.financial&&<th>收款狀態</th>}</tr></thead><tbody>{data.orders.slice(0,8).map(o=><tr key={o.id}><td><button className="order-link" onClick={()=>openOrder(o.number)}>{o.number}</button></td><td>{o.customer}</td><td>{o.orderedAt.slice(0,10)}</td><td className="numeric">{o.currency} {money(o.total)}</td><td><Status value={orderStatus(o)}/></td>{data.user.financial&&<td>{o.due!==null?<Status value={Number(o.due)>0?'未收清':'已收清'}/>: '—'}</td>}</tr>)}</tbody></table></div>{!data.orders.length&&<div className="designed-empty"><h3>尚無銷售訂單</h3><p>新增銷售單後可查詢出貨及收款狀態。</p><button className="quiet" onClick={()=>navigate('sales')}>前往銷售與出貨</button></div>}</section>
 </div>;
}
