'use client';
import {useState} from 'react';
export type Product={id:string;code:string;name:string;groupName:string;unit:string;price:string;active:boolean;updatedAt:string;hasHistory:boolean;stock:number;pending:number};
export default function ProductManagement({products,manage,busy,save}:{products:Product[];manage:boolean;busy:boolean;save:(input:Record<string,unknown>)=>Promise<boolean>}){
 const [editing,setEditing]=useState<string|null>(null),[filter,setFilter]=useState('active');
 const current=products.find(p=>p.id===editing);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!current)return;const values=Object.fromEntries(new FormData(e.currentTarget));if(await save({...values,action:'editSku',id:current.id,expectedUpdatedAt:current.updatedAt}))setEditing(null);}
 async function action(p:Product,action:string){const message=action==='deleteSku'?`永久刪除誤建商品「${p.code} · ${p.name}」？商品資料無法復原，操作紀錄仍會保留。`:action==='disableSku'?`停用「${p.code} · ${p.name}」？之後不能新增進貨或銷售，歷史帳務保留。`:`重新啟用「${p.code} · ${p.name}」？`;if(window.confirm(message))await save({action,id:p.id,expectedUpdatedAt:p.updatedAt});}
 return <><h3>商品目錄</h3><label>顯示商品<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">使用中</option><option value="inactive">已停用</option><option value="all">全部商品</option></select></label>
 {manage&&<p>可編輯名稱、系列、單位與參考售價。已有交易紀錄不可刪除；庫存與待出貨皆為 0 才可停用。</p>}
 {manage&&current&&<section className="subrecord" aria-label="編輯商品"><h3>編輯商品：{current.code}</h3><p>單位修改只更正顯示文字，不會把盒換算成支，也不會改變庫存數量。單位請填「支」或「kg」，不要填入數量。</p><form key={current.id+current.updatedAt} onSubmit={submit}><fieldset disabled={busy}><div className="form-grid"><label>商品名稱<input name="name" defaultValue={current.name} maxLength={160} required/></label><label>商品系列<input name="groupName" defaultValue={current.groupName} maxLength={160}/></label><label>庫存單位<input name="unit" defaultValue={current.unit} maxLength={20} required/></label><label>參考售價（AUD）<input name="price" type="number" min="0" step="0.01" defaultValue={current.price} required/></label></div><button className="primary">儲存商品</button> <button type="button" className="quiet" onClick={()=>setEditing(null)}>取消編輯</button></fieldset></form></section>}
 <div className="table-scroll"><table><thead><tr><th>SKU／商品</th><th>系列／單位</th><th>參考售價 AUD</th><th>狀態</th>{manage&&<th>管理</th>}</tr></thead><tbody>{products.filter(p=>filter==='all'||p.active===(filter==='active')).map(p=><tr key={p.id}><td>{p.code}<small>{p.name}</small></td><td>{p.groupName||'—'}<small>{p.unit}</small></td><td>{Number(p.price).toFixed(2)}</td><td>{p.active?'使用中':'已停用'}</td>{manage&&<td><button className="quiet" disabled={busy} onClick={()=>setEditing(p.id)}>編輯</button> {p.active?<button className="quiet" disabled={busy||p.stock>0||p.pending>0} onClick={()=>void action(p,'disableSku')}>停用</button>:<button className="quiet" disabled={busy} onClick={()=>void action(p,'enableSku')}>重新啟用</button>} <button className="danger" disabled={busy||p.hasHistory} onClick={()=>void action(p,'deleteSku')}>刪除</button>{p.hasHistory&&<small>已有交易紀錄，不可刪除</small>}{p.active&&(p.stock>0||p.pending>0)&&<small>尚有庫存 {p.stock}／待出貨 {p.pending}，不可停用</small>}</td>}</tr>)}</tbody></table></div>{!products.some(p=>filter==='all'||p.active===(filter==='active'))&&<p className="empty">沒有符合條件的商品。</p>}</>;
}
