'use client';
import {useState} from 'react';
import type {Order} from './workspace';
import {money,orderStatus,Status,MiniIcon} from './presentation';
type Props={orders:Order[];allOrders:Order[];financial:boolean;search:string;setSearch:(s:string)=>void;canSale:boolean;canShip:boolean;busy:boolean;canReverse:boolean;openForm:(mode:'sale'|'ship')=>void;preview:(order:string,shipment?:string)=>void;reverse:(id:string)=>void};
export default function SalesList({orders,allOrders,financial,search,setSearch,canSale,canShip,busy,canReverse,openForm,preview,reverse}:Props){
 const [filter,setFilter]=useState('全部訂單');
 const filters=['全部訂單','待出貨','部分出貨','已出貨',...(financial?['未收清']:[])];
 const matches=(o:Order,f:string)=>f==='全部訂單'||(f==='未收清'?o.due!==null&&Number(o.due)>0:orderStatus(o)===f);
 const shown=orders.filter(o=>matches(o,filter));
 return <div className="sales-view"><div className="sales-toolbar"><div><span className="section-kicker">ORDER MANAGEMENT</span><h2>銷售訂單<small>共 {allOrders.length} 張訂單</small></h2></div><div className="toolbar-actions">{canShip&&<button className="quiet" disabled={busy} onClick={()=>openForm('ship')}>安排出貨 ↗</button>}{canSale&&<button className="primary" disabled={busy} onClick={()=>openForm('sale')}>＋ 新增銷售單</button>}</div></div>
 <section className="panel sales-panel"><div className="sales-filters"><div className="filter-tabs" role="group" aria-label="訂單狀態篩選">{filters.map(f=><button key={f} aria-pressed={filter===f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f}<span>{allOrders.filter(o=>matches(o,f)).length}</span></button>)}</div><label className="search-box"><span className="sr-only">搜尋訂單</span><input aria-label="搜尋訂單" placeholder="搜尋訂單、客戶或 SKU…" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
 <div className="order-list-heading"><span>訂單／客戶</span><span>出貨與收款</span><span className="numeric">訂單金額</span><span/></div>
 {shown.map(o=><details className="order-card" key={o.id}><summary><span className="order-identity"><strong>{o.number}</strong><small>{o.customer} <span>· {o.orderedAt.slice(0,10)}</span></small></span><span className="order-statuses"><Status value={orderStatus(o)}/>{financial&&o.due!==null&&<Status value={Number(o.due)>0?'未收清':'已收清'}/>}</span><span className="order-amount"><small>{o.currency}</small><strong>{money(o.total)}</strong></span><span className="expand-order" aria-hidden="true">⌄</span></summary>
 <div className="order-expanded"><div className="order-section-heading"><h3>商品明細 <small>{o.lines.length} 項</small></h3><button className="quiet" onClick={()=>preview(o.id)}>預覽訂單圖片</button></div><div className="table-scroll"><table><thead><tr><th>商品／SKU</th><th className="numeric">訂購數量</th><th className="numeric">單價 · {o.currency}</th><th className="numeric">待出數量</th></tr></thead><tbody>{o.lines.map(l=><tr key={l.id}><td>{l.name}<small>{l.sku}</small></td><td className="numeric">{l.quantity}</td><td className="numeric">{money(l.price)}</td><td className="numeric">{l.remaining}</td></tr>)}</tbody></table></div>
 {financial&&<div className="order-financials"><div><small>已收 · {o.currency}</small><strong>{money(o.paid)}</strong></div><div><small>未收 · {o.currency}</small><strong>{money(o.due)}</strong></div><div><small>出貨成本 · AUD</small><strong>{money(o.cost)}</strong></div><div><small>出貨毛利 · AUD</small><strong>{money(o.profit)}</strong></div></div>}
 {o.note&&<p className="order-note"><strong>訂單備註</strong>{o.note}</p>}
 <div className="order-section-heading shipment-heading"><h3>出貨紀錄 <small>{o.shipments.length} 筆</small></h3></div>
 {!o.shipments.length&&<p className="shipment-empty">尚未出貨，安排出貨後即可在這裡追蹤倉庫與批次。</p>}
 {o.shipments.map(s=><div className="shipment-card" key={s.id}><div className="shipment-top"><div><strong>{s.number}</strong> <Status value={s.state==='POSTED'?'已出貨':'已沖銷'}/></div><button className="quiet" onClick={()=>preview(o.id,s.id)}>預覽本次出貨圖片</button></div><p className="shipment-meta">{s.time.slice(0,10)} · {s.warehouse} → {o.customer} · 經手人 {s.actor}</p><div className="shipment-allocations">{s.allocations.map((a,i)=><div key={i}><span>{a.sku}<small>批次 {a.batch}</small></span><strong>{a.quantity} 件</strong>{financial&&<span>單位成本 AUD {money(a.cost)}</span>}</div>)}</div>{s.note&&<p className="order-note">備註：{s.note}</p>}{canReverse&&s.state==='POSTED'&&<button disabled={busy} className="danger" onClick={()=>reverse(s.id)}>沖銷出貨並回庫</button>}</div>)}
 </div></details>)}
 {!shown.length&&<div className="designed-empty"><MiniIcon kind="orders"/><h3>{allOrders.length?'沒有符合的訂單':'尚無銷售訂單'}</h3><p>{allOrders.length?'試著調整搜尋內容或切換訂單狀態。':'新增銷售單後可安排出貨與查詢款項。'}</p>{allOrders.length?<button className="quiet" onClick={()=>{setSearch('');setFilter('全部訂單');}}>清除篩選</button>:canSale&&<button className="primary" onClick={()=>openForm('sale')}>＋ 新增銷售單</button>}</div>}
 <div className="list-footer">顯示 {shown.length} / {allOrders.length} 張訂單<span>展開訂單查看商品、款項與出貨紀錄</span></div></section></div>;
}
