'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import ProductManagement, {type Product} from './product-management';
import DocumentPreview from './document-preview';
import AccountManagement from './account-management';
import { signOutAction } from '@/app/actions/auth';
type StockRow={id:string;name:string;code?:string;group?:string;unit:string;total:number;warehouses:{id:string;name:string;quantity:number}[]};
type Batch={originalCost:string;costVersion:number;remainingValue:string;adjustments:{id:string;version:number;oldCost:string;newCost:string;quantity:number;valueChangeAud:string;warehouses:{id:string;name:string;quantity:number}[];date:string;actor:string;reason:string}[];id:string;batch:string;label:string;sku:string;name:string;unit:string;date:string;supplier:string;warehouse:string;note:string;currency:string;fxToAud:string|null;unitCost:string;totalCost:string;received:number;shipped:number;remaining:number;revenue:string|null;paid:string|null;due:string|null;cost:string|null;profit:string|null;warehouses:{name:string;quantity:number}[];rows:{lockedCost:string|null;costVersion:number;id:string;order:string;customer:string;date:string;actor:string;warehouse:string;quantity:number;price:string;currency:string;receivable:string;paid:string;due:string}[]};
type Option={note?:string;id:string;name:string;code?:string;price?:string};
type Order={currency:string;note:string;orderedAt:string;advance:string|null;id:string;number:string;customerId:string;customer:string;total:string;paid:string|null;due:string|null;cost:string|null;profit:string|null;lines:{id:string;name:string;sku:string;quantity:number;price:string;remaining:number}[];shipments:{id:string;number:string;state:string;time:string;warehouse:string;actor:string;note:string;allocations:{sku:string;batch:string;quantity:number;cost:string|null}[]}[];payments:{id:string;number:string;amount:string;state:string;actor:string;time:string;note:string}[]};
type Data={productCatalog:Product[];inventory:StockRow[];groups:StockRow[];batches:Batch[];customerSummaries:{currency:string;id:string;name:string;total:string;paid:string;due:string}[];totals:{due:string|null;profit:string|null};user:{id:string;email:string;admin:boolean;name:string;manager:boolean;financial:boolean;permissions:string[]};skus:Option[];warehouses:Option[];customers:Option[];suppliers:Option[];balances:{currency:string;sku:string;name:string;warehouse:string;batch:string;quantity:number;cost:string|null;receivedAt:string}[];orders:Order[];receipts:{note:string;id:string;number:string;state:string;time:string;warehouse:string;actor:string;lines:{sku:string;batch:string;quantity:number;cost:string;currency:string;label:string;date:string;supplier:string}[]}[];events:{id:string;action:string;entityId:string;reason:string|null;time:string;actor:string}[];employees:{id:string;email:string;displayName:string;employeeRole:string|null;role:string;active:boolean}[]};
const tabs=[['overview','營運總覽'],['stock','商品與庫存'],['receive','採購入庫'],['batches','批次帳務'],['sales','銷售與出貨'],['payments','客戶帳款'],['settings','基礎資料'],['audit','操作紀錄'],['accounts','帳號管理']];
const money=(v:string|number|null)=>v===null?'—':Number(v).toLocaleString('zh-TW',{minimumFractionDigits:2,maximumFractionDigits:2});
const date=(s:string)=>s?new Date(s).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour12:false}):'—';
const businessDay=(s:string)=>s?s.slice(0,10):'—';
function Select({name,label,options,onChange}:{name:string;label:string;options:Option[];onChange?:(id:string)=>void}){return <label>{label}<select name={name} required onChange={e=>onChange?.(e.target.value)} defaultValue=""><option value="" disabled>請選擇</option>{options.map(o=><option key={o.id} value={o.id}>{o.code?o.code+' · ':''}{o.name}</option>)}</select></label>;}
function Field({name,label,type='text',...props}:{name:string;label:string;type?:string;min?:string;step?:string;defaultValue?:string;minLength?:number}){return <label>{label}<input name={name} type={type} required {...props}/></label>;}
function Lines({skus,cost=false}:{skus:Option[];cost?:boolean}){const [rows,setRows]=useState([0]);return <div className="line-editor">{rows.map((r,i)=><div className="form-grid" key={r}><Select name={'sku'+i} label="商品 SKU" options={skus}/><Field name={'qty'+i} label="數量" type="number" min="1" step="1" defaultValue="1"/><Field name={'price'+i} label={cost?"進貨單位成本（所選幣別）":"銷售單價（所選幣別）"} type="number" min="0" step={cost?"0.0001":"0.01"}/>{rows.length>1&&<button type="button" className="quiet" onClick={()=>setRows(rows.filter(x=>x!==r))}>移除</button>}</div>)}<input type="hidden" name="lineCount" value={rows.length}/><button type="button" className="quiet" onClick={()=>setRows([...rows,Math.max(...rows)+1])}>＋ 新增明細</button></div>;}
export default function Workspace(){
 const [data,setData]=useState<Data|null>(null),[tab,setTab]=useState('overview'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[search,setSearch]=useState(''),[selected,setSelected]=useState('');
 const [documentTarget,setDocumentTarget]=useState<{orderId:string;shipmentId?:string}|null>(null);
 const keys=useRef(new Map<string,string>());const sending=useRef(false);
 const load=useCallback(async()=>{const r=await fetch('/api/erp',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);},[]);
 useEffect(()=>{load().catch(e=>setError(e.message));},[load]);
 async function send(input:Record<string,unknown>,form?:HTMLFormElement){if(sending.current)return false;sending.current=true;setBusy(true);setError('');setMessage('');const fingerprint=JSON.stringify(input);const requestKey=keys.current.get(fingerprint)||crypto.randomUUID();keys.current.set(fingerprint,requestKey);
 try{const r=await fetch('/api/erp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,requestKey})});const result=await r.json();if(!r.ok){keys.current.delete(fingerprint);throw Error(result.error);}keys.current.delete(fingerprint);form?.reset();setSelected('');setMessage('已完成，資料已更新。');await load();return true;}catch(e){setError(e instanceof Error?e.message:'連線失敗，請重試');return false;}finally{sending.current=false;setBusy(false);}}
 function submit(action:string){return (e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const input:Record<string,unknown>={action};for(const [k,v] of f.entries())input[k]=v;
 if(action==='receive'||action==='sale'){input.lines=Array.from({length:Number(f.get('lineCount'))},(_,i)=>({skuId:f.get('sku'+i),quantity:Number(f.get('qty'+i)),price:f.get('price'+i)}));}
 if(action==='ship'){const order=data?.orders.find(o=>o.id===f.get('orderId'));input.lines=order?.lines.map(l=>({lineId:l.id,quantity:Number(f.get(l.id)||0)})).filter(l=>l.quantity>0);}
 void send(input,form);};}
 function reverse(kind:string,id:string){const reason=window.prompt('請輸入沖銷原因。沖銷會保留原單據及紀錄。');if(reason?.trim())void send({action:'reverse',kind,id,reason:reason.trim()});}
 const allowed=(a:string)=>data?.user.permissions.includes(a);
 const button=(title:string)=><button className="primary" disabled={busy}>{busy?'處理中…':title}</button>;
 if(!data)return <main className="erp-loading"><h1>庫務 ERP</h1><p role="alert">{error||'正在讀取工作區…'}</p>{error&&<button onClick={()=>{setError('');void load().catch(e=>setError(e.message));}}>重新讀取</button>}<a href="/login">返回登入</a></main>;
 const stock=data.balances.filter(b=>[b.sku,b.name,b.warehouse,b.batch].join(' ').toLowerCase().includes(search.toLowerCase()));
 const orders=data.orders.filter(o=>[o.number,o.customer,...o.lines.map(l=>l.sku)].join(' ').toLowerCase().includes(search.toLowerCase()));
 const order=data.orders.find(o=>o.id===selected);
 return <div className="erp-shell"><aside className="erp-sidebar"><a href="/erp" className="erp-brand"><span className="erp-mark">庫</span><div>庫務 ERP<small>INVENTORY WORKSPACE</small></div></a><div className="nav-label">工作空間</div><nav>{tabs.filter(([k])=>!(['payments','receive','batches'].includes(k)&&!data.user.financial)&&!(k==='audit'&&!data.user.manager)).map(([k,title])=><button key={k} className={tab===k?'active':''} onClick={()=>{setTab(k);setSearch('');setSelected('');}}><span>{String(tabs.findIndex(t=>t[0]===k)+1).padStart(2,'0')}</span>{title}</button>)}</nav><div className="sidebar-bottom"><strong>{data.user.name}</strong><small>主要幣別 AUD · 支援 CNY</small><form action={signOutAction}><button>登出帳號 ↗</button></form></div></aside>
 <main className="erp-main"><header><div><p className="erp-eyebrow">OPERATIONS / {tab.toUpperCase()}</p><h1>{tabs.find(t=>t[0]===tab)?.[1]}</h1><p>掌握每一批商品，讓庫存與帳款都有跡可循。</p></div><button className="quiet" disabled={busy} onClick={()=>void load().catch(e=>setError(e.message))}>重新整理 ↻</button></header>
 {error&&<div className="notice error" role="alert">{error}</div>}{message&&<div className="notice" role="status">{message}</div>}
 {tab==='overview'&&<><div className="metrics"><article><small>商品 SKU</small><strong>{data.skus.length}</strong><span>獨立管理每個商品規格</span></article><article><small>現有庫存</small><strong>{[...new Set(data.inventory.map(r=>r.unit))].map(unit=><span key={unit}>{data.inventory.filter(r=>r.unit===unit).reduce((v,r)=>v+r.total,0)}<em>{unit}</em> </span>)}</strong><span>{data.warehouses.length} 個倉庫</span></article>{data.user.financial&&<><article><small>客戶未收款 · AUD</small><strong>{money(data.totals.due)}</strong><span>換算澳幣，包含尚未出貨訂單</span></article><article><small>已出貨毛利 · AUD</small><strong>{money(data.totals.profit)}</strong><span>換算澳幣，尚無匯率則顯示 —</span></article></>}</div><section className="panel"><div className="section-heading"><h2>開始你的營運流程</h2><span>01 → 04</span></div><div className="steps">{[['settings','建立倉庫與往來對象','設定倉庫、供應商與客戶'],['stock','建立商品 SKU','每個規格對應固定編碼'],['receive','登錄採購入庫','每批進貨保留獨立成本'],['sales','建立訂單與出貨','先進先出，自動追蹤批次']].map(([key,title,desc],i)=><button key={key} onClick={()=>setTab(key)}><small>0{i+1}</small><h3>{title}</h3><p>{desc}</p></button>)}</div></section><section className="panel"><h2>最近訂單</h2><div className="table-scroll"><table><thead><tr><th>訂單</th><th>客戶</th><th>銷售額</th><th>出貨進度</th></tr></thead><tbody>{data.orders.slice(0,8).map(o=><tr key={o.id}><td>{o.number}</td><td>{o.customer}</td><td>{o.currency} {money(o.total)}</td><td>{o.lines.reduce((s,l)=>s+l.quantity-l.remaining,0)} / {o.lines.reduce((s,l)=>s+l.quantity,0)} 件</td></tr>)}</tbody></table></div>{!data.orders.length&&<p className="empty">尚無訂單。完成商品與客戶設定後，即可建立第一張銷售單。</p>}</section></>}
 {tab==='stock'&&<>{allowed('sku')&&<section className="panel"><h2>新增商品 SKU</h2><form onSubmit={submit('sku')}><div className="form-grid"><Field name="code" label="SKU 編碼"/><Field name="name" label="商品名稱／規格"/><label>商品系列（例如 IGET ONE）<input name="groupName" maxLength={160}/></label><Field name="unit" label="庫存單位" defaultValue="支"/><Field name="price" label="參考售價（AUD，可留 0）" type="number" min="0" step="0.01" defaultValue="0"/></div>{button('建立商品')}</form></section>}<section className="panel"><h2>各倉庫與總庫存</h2><p>相同 SKU 的各倉庫數量自動加總；商品系列依相同單位彙總。</p><InventoryTable rows={data.inventory.filter(r=>[r.code,r.name,r.group].join(" ").toLowerCase().includes(search.toLowerCase()))} warehouses={data.warehouses}/>{data.groups.length>0&&<><h3>商品系列總庫存</h3><InventoryTable rows={data.groups} warehouses={data.warehouses}/></>}<ProductManagement products={data.productCatalog} manage={!!allowed('editSku')} busy={busy} save={send}/></section><section className="panel"><div className="section-heading"><h2>倉庫批次庫存</h2><input aria-label="搜尋庫存" placeholder="搜尋商品、倉庫或批次" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="table-scroll"><table><thead><tr><th>SKU／商品</th><th>倉庫</th><th>批次</th><th>數量</th>{data.user.financial&&<th>目前單位成本</th>}<th>入庫時間</th></tr></thead><tbody>{stock.map(b=><tr key={b.warehouse+b.batch}><td>{b.sku}<small>{b.name}</small></td><td>{b.warehouse}</td><td>{b.batch}</td><td>{b.quantity}</td>{data.user.financial&&<td>{b.currency} {money(b.cost)}</td>}<td>{businessDay(b.receivedAt)}</td></tr>)}</tbody></table></div>{!stock.length&&<p className="empty">沒有符合條件的批次庫存。</p>}</section></>}
 {tab==='receive'&&<>{allowed('receive')&&<section className="panel"><h2>採購入庫</h2><p>確認後立即入庫，每個明細建立獨立成本批次。單價請填入已分攤費用的成本。</p><form onSubmit={submit('receive')}><CurrencyFields/><DocumentFields label="入庫日期"/><label>批次名稱／供應商批號（選填）<input name="batchLabel" maxLength={160}/></label><div className="form-grid"><Select name="supplierId" label="供應商" options={data.suppliers}/><Select name="warehouseId" label="入庫倉庫" options={data.warehouses}/></div><Lines skus={data.skus} cost/>{button('確認採購並入庫')}</form></section>}<section className="panel"><h2>入庫紀錄 <small>最近 200 筆</small></h2>{data.receipts.map(r=><details key={r.id}><summary>{r.number} · {r.warehouse} · {r.state==='POSTED'?'已入庫':'已沖銷'}<small>{date(r.time)} · {r.actor}</small></summary><p>備註：{r.note||'—'}</p>{r.lines.map(l=><p key={l.batch}>{l.supplier} ／ {l.sku} ／ {l.batch} ／ {l.quantity} × {l.currency} {money(l.cost)} ／ {l.label} ／ 入庫日期 {businessDay(l.date)}</p>)}{allowed('reverse')&&r.state==='POSTED'&&<button disabled={busy} className="danger" onClick={()=>reverse('receipt',r.id)}>沖銷入庫</button>}</details>)}</section></>}
 {tab==='sales'&&<>{allowed('sale')&&<section className="panel"><h2>建立銷售單</h2><form onSubmit={submit('sale')}><CurrencyFields/><DocumentFields label="銷售日期"/><p>售價每次手動輸入，不受客戶或參考售價限制。</p><Select name="customerId" label="客戶" options={data.customers}/><Lines skus={data.skus}/>{button('建立銷售單')}</form></section>}{allowed('ship')&&<section className="panel"><h2>從倉庫出貨</h2><p>自動依 FIFO 分配批次，可分次出貨；未出貨的明細填 0。</p><form onSubmit={submit('ship')}><DocumentFields label="出貨日期"/><div className="form-grid"><Select name="orderId" label="訂單" options={data.orders.filter(o=>o.lines.some(l=>l.remaining>0)).map(o=>({id:o.id,name:o.number+' · '+o.customer}))} onChange={setSelected}/><Select name="warehouseId" label="出貨倉庫" options={data.warehouses}/></div>{order?.lines.filter(l=>l.remaining>0).map(l=><label key={l.id}>{l.sku} · {l.name}（待出 {l.remaining} 件）<input name={l.id} type="number" min="0" max={l.remaining} step="1" defaultValue="0"/></label>)}{button('確認 FIFO 出庫')}</form></section>}<section className="panel"><div className="section-heading"><h2>銷售訂單</h2><input aria-label="搜尋訂單" placeholder="訂單、客戶或 SKU" value={search} onChange={e=>setSearch(e.target.value)}/></div>{orders.map(o=><details key={o.id}><summary>{o.number} · {o.customer}<small>銷售額 {o.currency} {money(o.total)}{data.user.financial?' ／ 出貨成本 AUD '+money(o.cost)+' ／ 毛利 AUD '+money(o.profit):''}</small></summary><button className="quiet" onClick={()=>setDocumentTarget({orderId:o.id})}>預覽訂單圖片</button><p>銷售日期 {businessDay(o.orderedAt)} · 備註：{o.note||'—'}</p>{o.lines.map(l=><p key={l.id}>{l.sku} · {l.name} ／ {l.quantity} 件 × {money(l.price)} ／ 待出 {l.remaining} 件</p>)}{o.shipments.map(s=><div className="subrecord" key={s.id}><strong>{s.number} · {s.state==='POSTED'?'已出貨':'已沖銷'}</strong><button className="quiet" onClick={()=>setDocumentTarget({orderId:o.id,shipmentId:s.id})}>預覽本次出貨圖片</button><p>{businessDay(s.time)} · {s.actor} 從 {s.warehouse} 出貨給 {o.customer}</p><p>備註：{s.note||'—'}</p>{s.allocations.map((a,i)=><p key={i}>{a.sku} ／ 批次 {a.batch} ／ {a.quantity} 件{data.user.financial?' ／ 單位成本 AUD '+money(a.cost):''}</p>)}{allowed('reverse')&&s.state==='POSTED'&&<button disabled={busy} className="danger" onClick={()=>reverse('shipment',s.id)}>沖銷出貨並回庫</button>}</div>)}</details>)}{!orders.length&&<p className="empty">尚無符合條件的訂單。</p>}</section></>}
 {tab==='payments'&&<>{allowed('payment')&&<section className="panel"><h2>登錄收款</h2><p>支援分次收款，款項直接沖抵所選訂單。</p><form onSubmit={submit('payment')}><DocumentFields label="收款日期"/><div className="form-grid"><Select name="orderId" label="訂單" options={data.orders.filter(o=>Number(o.due)>0).map(o=>({id:o.id,name:o.number+' · '+o.customer+' · 未收 '+o.currency+' '+money(o.due)}))}/><Field name="amount" label="本次收款（與所選訂單同幣別）" type="number" min="0.01" step="0.01"/></div>{button('確認收款')}</form></section>}<section className="panel"><h2>客戶欠款</h2><div className="table-scroll"><table><thead><tr><th>客戶</th><th>訂單總額</th><th>已收</th><th>未收</th></tr></thead><tbody>{data.customerSummaries.map(c=><tr key={c.id}><td>{c.name} · {c.currency}</td><td>{money(c.total)}</td><td>{money(c.paid)}</td><td>{money(c.due)}</td></tr>)}</tbody></table></div></section><section className="panel"><h2>訂單收款明細</h2>{data.orders.map(o=><details key={o.id}><summary>{o.number} · {o.customer}<small>{o.currency} 已收 {money(o.paid)} ／ 未收 {money(o.due)} ／ 未分配至出貨批次 {money(o.advance)}</small></summary>{o.payments.map(p=><div className="subrecord" key={p.id}><p>{p.number} · {money(p.amount)} · {p.state==='POSTED'?'已收款':'已沖銷'}</p><small>{businessDay(p.time)} · {p.actor}</small><p>備註：{p.note||'—'}</p>{allowed('reverse')&&p.state==='POSTED'&&<button disabled={busy} className="danger" onClick={()=>reverse('payment',p.id)}>沖銷收款</button>}</div>)}</details>)}</section></>}
 {tab==='settings'&&<>{[['warehouse','倉庫',data.warehouses],['customer','客戶',data.customers],['supplier','供應商',data.suppliers]].map(([action,title,list])=><section className="panel" key={String(action)}><h2>{String(title)}</h2>{allowed(String(action))&&<form onSubmit={submit(String(action))}><div className="form-grid"><Field name="code" label="編碼"/><Field name="name" label="名稱"/>{action!=='warehouse'&&<label>備註（選填）<input name="note" maxLength={2000}/></label>}</div>{button('新增'+title)}</form>}<div className="chips">{(list as Option[]).map(o=><span key={o.id}>{o.code} · {o.name}{o.note&&<small>{o.note}</small>}</span>)}</div></section>)}{allowed('employee')&&<section className="panel"><h2>員工與權限</h2><form onSubmit={submit('employee')}><div className="form-grid"><Field name="email" label="Email" type="email"/><Field name="name" label="員工姓名"/><Field name="password" label="初始密碼（至少 8 碼）" type="password" minLength={8}/><label>權限<select name="role"><option value="WAREHOUSE">倉管：查庫存、出貨</option><option value="SALES">業務：客戶、銷售單</option><option value="FINANCE">財務：帳款、收款</option><option value="MANAGER">主管：全部 ERP 功能</option></select></label></div>{button('建立員工')}</form>{data.employees.map(e=><div className="employee" key={e.id}><span>{e.displayName||e.email}<small>{e.email} · {e.role==='ADMIN'?'系統管理員':e.employeeRole} · {e.active?'啟用':'停用'}</small></span>{e.active&&e.role!=='ADMIN'&&<button disabled={busy} className="danger" onClick={()=>{if(confirm('確認停用此員工？'))void send({action:'disableEmployee',id:e.id});}}>停用</button>}</div>)}</section>}</>}
 {tab==='batches'&&data.user.financial&&<section className="panel"><h2>每批貨的成本、出貨與帳款</h2><p>批次應收僅計已出貨部分。收款依出貨先後分配；剩餘為訂單預收款。毛利 = 已出貨銷售額 − 已出貨成本，未扣其他營運費用。</p><input aria-label="搜尋批次帳務" placeholder="商品、批次或供應商" value={search} onChange={e=>setSearch(e.target.value)}/>{data.batches.filter(b=>[b.sku,b.name,b.batch,b.label,b.supplier].join(' ').toLowerCase().includes(search.toLowerCase())).map(b=><details key={b.id}><summary>{b.label||b.batch} · {b.sku} · {b.name}<small>{b.supplier} ／ 入庫 {b.received} ／ 出貨 {b.shipped} ／ 庫存 {b.remaining} {b.unit}</small></summary><p>{businessDay(b.date)} · 入庫倉庫 {b.warehouse} · 系統批號 {b.batch}</p><p>原始進貨單價 {b.currency} {money(b.originalCost)} · 進貨總成本 {b.currency} {money(b.totalCost)} · 1 {b.currency} = {b.fxToAud||'待補'} AUD</p><p>目前庫存單位成本 {b.currency} {money(b.unitCost)} · 剩餘庫存成本 {b.currency} {money(b.remainingValue)} · 成本版本 {b.costVersion}</p><p>備註：{b.note||'—'}</p><p>{b.warehouses.map(w=>w.name+'：'+w.quantity+' '+b.unit).join(' ／ ')}</p><div className="chips"><span>出貨應收 AUD {money(b.revenue)}</span><span>實收 AUD {money(b.paid)}</span><span>未收 AUD {money(b.due)}</span><span>已出貨成本 AUD {money(b.cost)}</span><span>已出貨毛利 AUD {money(b.profit)}</span></div><div className="table-scroll"><table><thead><tr><th>日期／訂單</th><th>客戶</th><th>倉庫／操作人</th><th>數量</th><th>銷售單價</th><th>出貨鎖定成本</th><th>應收</th><th>實收</th><th>未收</th></tr></thead><tbody>{b.rows.map(r=><tr key={r.id}><td>{businessDay(r.date)}<small>{r.order}</small></td><td>{r.customer}</td><td>{r.warehouse}<small>{r.actor}</small></td><td>{r.quantity}</td><td>{r.currency} {money(r.price)}</td><td>AUD {money(r.lockedCost)}<small>版本 {r.costVersion}</small></td><td>{r.currency} {money(r.receivable)}</td><td>{r.currency} {money(r.paid)}</td><td>{r.currency} {money(r.due)}</td></tr>)}</tbody></table></div>{!b.rows.length&&<p className="empty">此批尚未出貨。</p>}
 {allowed('adjustBatchCost')&&b.remaining>0&&<div className="subrecord"><h3>調整剩餘庫存成本</h3><p>套用至此批全部倉庫共 {b.remaining} {b.unit}，不改數量；已出貨成本不變。立即生效，沿用入庫匯率，不能回溯。</p><form key={b.costVersion} onSubmit={submit('adjustBatchCost')}><input type="hidden" name="batchId" value={b.id}/><input type="hidden" name="expectedVersion" value={b.costVersion}/><div className="form-grid"><Field name="newCost" label={'新單位成本（'+b.currency+'）'} type="number" min="0" step="0.0001" defaultValue={b.unitCost}/><Field name="reason" label="調整原因"/></div>{button('確認調整剩餘成本')}</form></div>}
 <h3>成本調整歷史</h3>{b.adjustments.map(a=><div className="subrecord" key={a.id}><p>{date(a.date)} · {a.actor} · 版本 {a.version}</p><p>{b.currency} {money(a.oldCost)} → {money(a.newCost)} ／ 當時剩餘 {a.quantity} {b.unit} ／ 庫存價值調整 AUD {money(a.valueChangeAud)}</p><p>{a.warehouses.map(w=>w.name+'：'+w.quantity+' '+b.unit).join(' ／ ')}</p><p>原因：{a.reason}</p></div>)}{!b.adjustments.length&&<p>尚無成本調整。</p>}</details>)}{!data.batches.length&&<p className="empty">完成第一筆採購入庫後，即可追蹤每批貨。</p>}</section>}
 {tab==='accounts'&&<AccountManagement user={data.user} employees={data.employees}/>}
 {tab==='audit'&&data.user.manager&&<section className="panel"><h2>員工操作紀錄 <small>最近 200 筆</small></h2><div className="table-scroll"><table><thead><tr><th>時間</th><th>員工</th><th>操作</th><th>單據識別</th><th>原因</th></tr></thead><tbody>{data.events.map(e=><tr key={e.id}><td>{date(e.time)}</td><td>{e.actor}</td><td>{({adjustBatchCost:'調整剩餘庫存成本',editSku:'編輯商品',deleteSku:'刪除誤建商品',disableSku:'停用商品',enableSku:'重新啟用商品',sku:'新增商品',warehouse:'新增倉庫',customer:'新增客戶',supplier:'新增供應商',receive:'採購入庫',sale:'建立銷售',ship:'出庫',payment:'收款',reverse:'沖銷',employee:'新增員工',disableEmployee:'停用員工',changePassword:'修改自己的密碼',resetEmployeePassword:'管理員重設員工密碼'} as Record<string,string>)[e.action]||e.action}</td><td>{e.entityId}</td><td>{e.reason||'—'}</td></tr>)}</tbody></table></div></section>}
 {documentTarget&&<DocumentPreview {...documentTarget} onClose={()=>setDocumentTarget(null)}/>}
 <footer className="erp-footer">庫務 ERP · 批次成本採先進先出 · 主要幣別 AUD · 已過帳異動保留操作紀錄</footer></main></div>;
}

function CurrencyFields(){const [currency,setCurrency]=useState('AUD');return <div className="form-grid"><label>交易幣別<select name="currency" value={currency} onChange={e=>setCurrency(e.target.value)}><option value="AUD">AUD 澳幣</option><option value="CNY">CNY 人民幣</option></select></label>{currency==='CNY'?<Field name="fxToAud" label="匯率：1 CNY 等於多少 AUD" type="number" min="0.00000001" step="0.00000001"/>:<input name="fxToAud" type="hidden" value="1"/>}</div>;}
function DocumentFields({label}:{label:string}){return <div className="form-grid"><Field name="date" label={label} type="date" defaultValue={new Date().toLocaleDateString('en-CA')}/><label>備註（自由填寫）<input name="note" maxLength={2000}/></label></div>;}
function InventoryTable({rows,warehouses}:{rows:StockRow[];warehouses:Option[]}){return <div className="table-scroll"><table><thead><tr><th>商品／系列</th>{warehouses.map(w=><th key={w.id}>{w.name}</th>)}<th>總庫存</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.code&&<small>{r.code}</small>}{r.name}{r.group&&<small>{r.group}</small>}</td>{r.warehouses.map(w=><td key={w.id}>{w.quantity} {r.unit}</td>)}<td><strong>{r.total} {r.unit}</strong></td></tr>)}</tbody></table>{!rows.length&&<p className="empty">尚無商品，新增 SKU 後即可看到各倉庫庫存。</p>}</div>;}
